//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeMRed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actualite
    {
        public int ActualiteId { get; set; }
        public int ActualiteTypeId { get; set; }
        public int LangueId { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string Libelle { get; set; }
        public string SEOCourt { get; set; }
        public string SEOLong { get; set; }
        public string Contenu { get; set; }
    
        public virtual ActualiteType ActualiteType { get; set; }
        public virtual Langue Langue { get; set; }
    }
}
