//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeMRed.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MRedEntities : DbContext
    {
        public MRedEntities()
            : base("name=MRedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actualite> Actualites { get; set; }
        public DbSet<ActualiteType> ActualiteTypes { get; set; }
        public DbSet<Categorie> Categories { get; set; }
        public DbSet<CategorieCritere> CategorieCriteres { get; set; }
        public DbSet<CategorieLangue> CategorieLangues { get; set; }
        public DbSet<ContenuHTML> ContenuHTMLs { get; set; }
        public DbSet<ContenuHTMLLangue> ContenuHTMLLangues { get; set; }
        public DbSet<Critere> Criteres { get; set; }
        public DbSet<CritereFamille> CritereFamilles { get; set; }
        public DbSet<CritereFamilleLangue> CritereFamilleLangues { get; set; }
        public DbSet<CritereLangue> CritereLangues { get; set; }
        public DbSet<ElementCarrousel> ElementCarrousels { get; set; }
        public DbSet<Enseigne> Enseignes { get; set; }
        public DbSet<Langue> Langues { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Produit> Produits { get; set; }
        public DbSet<ProduitCritere> ProduitCriteres { get; set; }
        public DbSet<ProduitImage> ProduitImages { get; set; }
        public DbSet<ProduitLangue> ProduitLangues { get; set; }
        public DbSet<Serie> Series { get; set; }
        public DbSet<SerieLangue> SerieLangues { get; set; }
    }
}
