//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeMRed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.CategorieCriteres = new HashSet<CategorieCritere>();
            this.CategorieLangues = new HashSet<CategorieLangue>();
            this.Produits = new HashSet<Produit>();
        }
    
        public int CategorieId { get; set; }
        public string Libelle { get; set; }
        public bool EstActif { get; set; }
    
        public virtual ICollection<CategorieCritere> CategorieCriteres { get; set; }
        public virtual ICollection<CategorieLangue> CategorieLangues { get; set; }
        public virtual ICollection<Produit> Produits { get; set; }
    }
}
