//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeMRed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CritereFamilleLangue
    {
        public int CritereFamilleLangueId { get; set; }
        public int CritereFamilleId { get; set; }
        public int LangueId { get; set; }
        public string Libelle { get; set; }
    
        public virtual CritereFamille CritereFamille { get; set; }
        public virtual Langue Langue { get; set; }
    }
}
