//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeMRed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Critere
    {
        public Critere()
        {
            this.CategorieCriteres = new HashSet<CategorieCritere>();
            this.CritereLangues = new HashSet<CritereLangue>();
            this.ProduitCriteres = new HashSet<ProduitCritere>();
        }
    
        public int CritereId { get; set; }
        public int CritereFamilleId { get; set; }
        public string Libelle { get; set; }
    
        public virtual ICollection<CategorieCritere> CategorieCriteres { get; set; }
        public virtual CritereFamille CritereFamille { get; set; }
        public virtual ICollection<CritereLangue> CritereLangues { get; set; }
        public virtual ICollection<ProduitCritere> ProduitCriteres { get; set; }
    }
}
