//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeMRed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Langue
    {
        public Langue()
        {
            this.Actualites = new HashSet<Actualite>();
            this.CategorieLangues = new HashSet<CategorieLangue>();
            this.ContenuHTMLLangues = new HashSet<ContenuHTMLLangue>();
            this.CritereFamilleLangues = new HashSet<CritereFamilleLangue>();
            this.CritereLangues = new HashSet<CritereLangue>();
            this.ElementCarrousels = new HashSet<ElementCarrousel>();
            this.Menus = new HashSet<Menu>();
            this.ProduitCriteres = new HashSet<ProduitCritere>();
            this.ProduitLangues = new HashSet<ProduitLangue>();
            this.SerieLangues = new HashSet<SerieLangue>();
        }
    
        public int LangueId { get; set; }
        public string Libelle { get; set; }
    
        public virtual ICollection<Actualite> Actualites { get; set; }
        public virtual ICollection<CategorieLangue> CategorieLangues { get; set; }
        public virtual ICollection<ContenuHTMLLangue> ContenuHTMLLangues { get; set; }
        public virtual ICollection<CritereFamilleLangue> CritereFamilleLangues { get; set; }
        public virtual ICollection<CritereLangue> CritereLangues { get; set; }
        public virtual ICollection<ElementCarrousel> ElementCarrousels { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<ProduitCritere> ProduitCriteres { get; set; }
        public virtual ICollection<ProduitLangue> ProduitLangues { get; set; }
        public virtual ICollection<SerieLangue> SerieLangues { get; set; }
    }
}
