//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeMRed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public string Societe { get; set; }
        public string Objet { get; set; }
        public string Telephone { get; set; }
        public string Mail { get; set; }
        public string Contenu { get; set; }
    }
}
