//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeMRed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public Produit()
        {
            this.ProduitCriteres = new HashSet<ProduitCritere>();
            this.ProduitImages = new HashSet<ProduitImage>();
            this.ProduitLangues = new HashSet<ProduitLangue>();
        }
    
        public int ProduitId { get; set; }
        public int CategorieId { get; set; }
        public string Libelle { get; set; }
        public string Reference { get; set; }
        public bool EstActif { get; set; }
        public string EAN { get; set; }
        public Nullable<int> ProduitIdJAJA { get; set; }
        public int SerieId { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual ICollection<ProduitCritere> ProduitCriteres { get; set; }
        public virtual ICollection<ProduitImage> ProduitImages { get; set; }
        public virtual ICollection<ProduitLangue> ProduitLangues { get; set; }
    }
}
