//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeMRed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduitImage
    {
        public int ProduitImageId { get; set; }
        public int ProduitId { get; set; }
        public string lien { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
