//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeMRed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public Serie()
        {
            this.SerieLangues = new HashSet<SerieLangue>();
        }
    
        public int SerieId { get; set; }
        public string Libelle { get; set; }
        public bool EstActif { get; set; }
    
        public virtual ICollection<SerieLangue> SerieLangues { get; set; }
    }
}
